services:
  mysql:
    image: mysql_reconfigured
    # This changed the authentication method of mysql so that the old
    # 'mysql-connector' python module could connect
    # command: --default-authentication-plugin=mysql_native_password
    # command: mysqld --general-log=1 --general-log-file=/dev/stdout
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${env_db_port_ext}:${env_db_port_int}"
    environment:
      MYSQL_ROOT_PASSWORD: ${env_db_password}
      MYSQL_DATABASE: ${env_db_name}
      MYSQL_LOG: 1
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s  # Check every 5 seconds
      timeout: 3s   # Timeout after 3 seconds
      retries: 3    # Retry up to 3 times before considering unhealthy
  app:
    build:
      context: app
    image: app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - env_db_password=${env_db_password}
      - env_db_name=${env_db_name}
    ports:
      - "${env_app_port}:${env_app_port}"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data:
