services:
  server:
    build:
      context: server
    networks:
      - my-internal-network
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
  hacker:
    build:
      context: hacker
    networks:
      - my-internal-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
  client:
    build:
      context: client
    networks:
      - my-internal-network

networks:
   my-internal-network:
     driver: bridge
