services:
  mysql:
    image: mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${env_db_port}:${env_db_port}"
    environment:
      MYSQL_ROOT_PASSWORD: ${env_db_password}
      MYSQL_DATABASE: ${env_db_name}
    volumes:
      - db-data:/var/lib/mysql
  app:
    build:
      context: app
    image: app
    # restart: unless-stopped
    env_file:
      - .env
    environment:
      - env_db_password=${env_db_password}
      - env_db_name=${env_db_name}
    ports:
      - "${env_app_port}:${env_app_port}"
    depends_on:
      - mysql 

volumes:
  db-data:
